import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header style={{backgroundColor:'white !important', color:'black !important', fontSize: '1.5rem' , padding:'20px'}}>Next JS Practice </header>
        
        {children}

        <footer style={{backgroundColor:'gray !important', color:'black !important', fontSize: '1.5rem' , padding:'20px'}}>Next JS Project all rights reserved xD</footer>
      </body>
    </html>
  );
}
